function trabajador(cargo,num) {
    this.cargo = cargo.value = Number(num++);
    this.rendimiento = Math.random(0,1);
    this.salario = Math.floor(Math.random(1250,400));
}


const trabajadores = [
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),
    new trabajador("cargo","rendimiento","salario"),


];



console.log(trabajadores);

 